package com.vaan.ultracarrier.collective

enum class MatrixKind {
    VACUUM, LANGUAGE, SOLITON, FRACTAL, NUMBER_MAP, HOLOGRAM, LIGHT, POLARIZATION, SPIN,
    PHASE, INTERFERENCE, RESONANCE, COHERENCE, BAND_SYMBOLIC, ULTRASONIC, HETERODYNE,
    SPECTRAL, TIME, MEMORY, FIELD, GEOMETRY, WATER, BIO, NOISE_ORDER, SIGNATURE, AUTO
}

enum class MatrixMode(
    val label: String,
    val description: String,
    val category: String,
    val kind: MatrixKind,
    val presetCarrier: Float? = null,
    val presetRate: Float? = 7.83f,
    val presetDepth: Float = .44f
) {
    VACUUM_POLARIZATION("Vacuum Polarization", "Source symmetry is progressively biased into an asymmetric phase/spectral representation.", "Vacuum / field models", MatrixKind.VACUUM, 18000f, 7.83f),
    ZERO_POINT_FIELD("Zero-Point / Vacuum Noise", "Procedural low-level noise, resonance and phase-order representation.", "Vacuum / field models", MatrixKind.VACUUM, null, 7.83f, .32f),
    LINGUISTIC_WAVE_GENETICS("Linguistic Wave Genetics", "Speech envelope is segmented into language-like tone cells and spectral motifs.", "Language / information", MatrixKind.LANGUAGE, null, 7f),
    LANGUAGE_TO_DNA("Language → DNA-Style Encoding", "Speech dynamics are quantized into a four-symbol harmonic alphabet.", "Language / information", MatrixKind.LANGUAGE, null, 7f),
    DNA_TO_LANGUAGE_MUSIC("DNA-Style → Language / Music", "Four-state information motifs are expanded into phrase-like harmonic gestures.", "Language / information", MatrixKind.LANGUAGE, null, 7f),
    ZIPF_LANGUAGE_MAP("Zipf / Language Frequency Map", "Tone occurrence is weighted toward a long-tail word-frequency style distribution.", "Language / information", MatrixKind.NUMBER_MAP, null, 7f),
    PRIME_NUMBER_MAP("Prime-Number Mapping", "Prime intervals drive event timing and frequency ratios.", "Mathematical mappings", MatrixKind.NUMBER_MAP, null, 11f),
    FIBONACCI_MAP("Fibonacci Mapping", "Fibonacci ratios drive timing, pitch spacing and modulation cycles.", "Mathematical mappings", MatrixKind.NUMBER_MAP, null, 8f),
    CODON_64_MAP("64-Codon Mapping", "Source states are quantized into sixty-four repeatable pitch/timbre positions.", "DNA / information", MatrixKind.NUMBER_MAP, null, 7f),
    SYNONYM_CODON("Synonym-Codon Mapping", "Different source patterns collapse to shared output motifs to model redundant code.", "DNA / information", MatrixKind.NUMBER_MAP, null, 7f),
    CONDUCTIVE_DNA_CHAIN("Conductive DNA Oscillator Chain", "A coupled helical oscillator chain models the transcript's conductive-strand hypothesis acoustically.", "DNA / field hypotheses", MatrixKind.RESONANCE, 12000f, 7.83f),
    ORGANIC_PARTICLE_ACCELERATOR("Organic Particle Accelerator", "Cascaded chirps, harmonics and circulating phase paths represent rising oscillator energy.", "Acceleration / chirp", MatrixKind.RESONANCE, 8000f, 4f),
    PINEAL_RESONANCE("Pineal Resonance", "Audio-derived damped resonance visualization/sonification associated with the transcript hypothesis.", "Bio / speculative resonance", MatrixKind.BIO, null, 10f),
    ORGANIC_UAP_RESONANCE("Organic UAP / Human-Craft Resonance", "Toroidal, helical, phase-locking and pulsed oscillator layers are combined acoustically.", "Bio / field architecture", MatrixKind.GEOMETRY, 12000f, 7.83f),
    BIOFIELD_SONIFICATION("Biofield Sonification", "Multiple source bands become circulating oscillator layers for body-map visualization.", "Bio / visualization", MatrixKind.BIO, null, 7.83f),
    PSYCHOTRONIC_SPECTRUM("Psychotronic-Inspired Spectrum", "Historical/fringe frequency-map representation for waveform comparison, not remote targeting.", "Historical / fringe map", MatrixKind.FIELD, 18000f, 7.83f),
    FIELD_PROPAGATION("Distance / Field Propagation", "Distance, attenuation, filtering, phase shift and interference are represented in stereo.", "Propagation / field", MatrixKind.FIELD, null, 7.83f),
    COHERENCE_DISRUPTION("Coherence / Disruption", "Continuously compares phase-aligned periodic structure against randomized broadband structure.", "Coherence / order", MatrixKind.COHERENCE, null, 7.83f),

    SOLITON_PULSE("Soliton Pulse", "Stable traveling sech-like pulse envelopes carry the source instead of continuous AM.", "Nonlinear / pulse", MatrixKind.SOLITON, 6000f, 4f),
    FRACTAL_SIGNAL("Fractal Signal", "Self-similar modulation repeats at slow, medium and fast time scales.", "Fractal / multiscale", MatrixKind.FRACTAL, null, 7.83f),
    FRACTAL_BIOLOGICAL_TIME("Fractal Biological Time", "The same modulation motif is repeated across stretched and compressed time scales.", "Fractal / multiscale", MatrixKind.FRACTAL, null, 7.83f),
    MULTISCALE_FRACTAL_TIME("Multi-Timescale Fractal Layer", "Slow, medium and rapid copies of the same information envelope are nested together.", "Fractal / multiscale", MatrixKind.FRACTAL, null, 7.83f),

    HOLOGRAPHIC_AUDIO("Holographic Audio", "One informational motif is distributed redundantly across multiple frequency bands.", "Holography / interference", MatrixKind.HOLOGRAM, 12000f, 6.18f),
    ACOUSTIC_HOLOGRAM("Acoustic Hologram Simulation", "Layered phase-coded carriers form a stereo hologram-style interference seed.", "Holography / interference", MatrixKind.HOLOGRAM, 18000f, 6.18f),
    EM_HOLOGRAM_SYMBOLIC("Electromagnetic Hologram Symbolic", "Audio drives several virtual modulated carriers represented acoustically.", "Holography / symbolic EM", MatrixKind.HOLOGRAM, 18000f, 7.83f),
    SOUND_TO_IMAGE_HOLOGRAM("Sound → Image Hologram", "Audio phase and spectrum drive the app's live geometric visualization.", "Holography / visualization", MatrixKind.HOLOGRAM, null, 7.83f),

    BIOPHOTON_SONIFICATION("Photon / Biophoton Sonification", "Source or imported intensity-like data is represented as pulse density and brightness-linked tone energy.", "Light / photon symbolic", MatrixKind.LIGHT, null, 7.83f),
    COHERENT_LIGHT("Coherent-Light Mode", "Highly phase-stable harmonic oscillators model laser-like coherence acoustically.", "Light / coherence", MatrixKind.LIGHT, 12000f, 7.83f),
    LASER_MODULATION("Laser Modulation", "Audio becomes AM/FM/phase data for a virtual optical carrier represented in sound.", "Light / modulation", MatrixKind.LIGHT, 12000f, 7.83f),
    HENE_632NM("632 nm He-Ne Reference", "632 nm is retained as optical metadata while an audible/acoustic mapped carrier is generated.", "Optical reference presets", MatrixKind.LIGHT, null, 7.83f),
    DNA_UV_390NM("390 nm DNA-UV Reference", "390 nm is retained as transcript-derived optical metadata and sonified.", "Optical reference presets", MatrixKind.LIGHT, null, 7.83f),
    RED_LIGHT("Red-Light Band", "Visible red wavelength band represented as a normalized audio mapping.", "Optical reference presets", MatrixKind.LIGHT, null, 7.83f),
    BLUE_LIGHT("Blue-Light Band", "Visible blue wavelength band represented as a normalized audio mapping.", "Optical reference presets", MatrixKind.LIGHT, null, 7.83f),
    ULTRAVIOLET("Ultraviolet Band", "UV band represented symbolically in the audio/visual mapper.", "Optical reference presets", MatrixKind.LIGHT, null, 7.83f),
    INFRARED("Infrared Band", "Infrared band represented symbolically in the audio/visual mapper.", "Optical reference presets", MatrixKind.LIGHT, null, 7.83f),
    NEAR_INFRARED("Near-Infrared Band", "Near-IR band represented symbolically in the audio/visual mapper.", "Optical reference presets", MatrixKind.LIGHT, null, 7.83f),
    VISIBLE_SPECTRUM_MAP("Visible-Spectrum Mapping", "Audio frequency position is mapped to visible-spectrum metadata and phase color visualization.", "Optical reference presets", MatrixKind.LIGHT, null, 7.83f),
    COLOR_FREQUENCY("Color ↔ Frequency", "Sound characteristics are mapped to color/light characteristics for synchronized visualization.", "Light / visualization", MatrixKind.LIGHT, null, 7.83f),
    PHOTON_POLARIZATION("Photon Polarization", "Audio controls a virtual polarization angle/state rendered as stereo phase.", "Polarization / spin", MatrixKind.POLARIZATION, 12000f, 7.83f),
    OPTICAL_ACTIVITY("Optical Activity", "Source amplitude rotates a simulated polarization angle and stereo phase.", "Polarization / spin", MatrixKind.POLARIZATION, 12000f, 7.83f),
    SPIN_MODULATION("Spin Modulation", "Audio is encoded into opposing plus/minus software spin states.", "Polarization / spin", MatrixKind.SPIN, 10000f, 7.83f),
    SPIN_INFORMATION_CARRIER("Spin Information Carrier", "Binary opposing spin-state symbolism carries thresholded source information.", "Polarization / spin", MatrixKind.SPIN, 10000f, 7.83f),
    BROADBAND_SPIN_CARRIER("Broadband Spin-Modulated Carrier", "Several acoustic carrier bands share opposing spin-state phase codes.", "Polarization / spin", MatrixKind.SPIN, 16000f, 7.83f),

    PHASE_CONJUGATE("Phase-Conjugate Matrix", "Forward and conjugate-like stereo phase paths are paired.", "Phase / interference", MatrixKind.PHASE, 18000f, 7.83f),
    PHASE_REVERSED("Phase-Reversed Audio", "The right channel carries an inverted/phase-reversed transformation of the source.", "Phase / interference", MatrixKind.PHASE, null, 7.83f),
    PHASE_OFFSET_STEREO("Precise Phase-Offset Stereo", "A continuously controlled interchannel phase offset is applied.", "Phase / stereo", MatrixKind.PHASE, 6000f, 7.83f),
    INTERFERENCE("Interference", "Original and delayed/phase-shifted copies interfere in stereo.", "Phase / interference", MatrixKind.INTERFERENCE, null, 7.83f),
    CONSTRUCTIVE_INTERFERENCE("Constructive Interference", "Delay and phase are pulled toward reinforcement points.", "Phase / interference", MatrixKind.INTERFERENCE, null, 7.83f),
    STANDING_WAVE_MATRIX("Standing-Wave Matrix", "Opposing virtual wave components create persistent nodes and antinodes.", "Phase / interference", MatrixKind.INTERFERENCE, 4000f, 7.83f),
    RESONANCE_LOCK("Resonance Lock", "Dominant source periodicity is tracked and a resonator follows it.", "Resonance / tracking", MatrixKind.RESONANCE, null, 7.83f),
    HARMONIC_RESONANCE_MATRIX("Harmonic / Subharmonic Resonance", "Harmonics and subharmonics are generated around a tracked source peak.", "Resonance / tracking", MatrixKind.RESONANCE, null, 7.83f),
    QUANTUM_OSCILLATOR_INSPIRED("Quantum-Oscillator Inspired", "Input bands are treated as coupled software oscillators exchanging phase and amplitude.", "Coupled oscillator models", MatrixKind.RESONANCE, null, 7.83f),
    FROHLICH_COHERENCE("Fröhlich-Coherence Inspired", "Many virtual oscillators gradually phase-lock into a dominant collective mode.", "Coupled oscillator models", MatrixKind.COHERENCE, null, 7.83f),
    FROHLICH_044THZ("0.44 THz Fröhlich Reference", "0.44 THz is retained as metadata while a scaled acoustic coherence pattern is generated.", "Reference frequency mappings", MatrixKind.COHERENCE, null, 7.83f),
    PHONON("Phonon Mode", "Mechanical/vibrational information is represented as quantized acoustic energy packets.", "Phonon / mechanical", MatrixKind.RESONANCE, null, 12f),
    PHOTON_PHONON("Photon-Phonon Hybrid", "A phase-stable virtual light oscillator is coupled to a damped mechanical oscillator.", "Phonon / mechanical", MatrixKind.RESONANCE, 10000f, 12f),
    MICROTUBULE_MULTIBAND("Microtubule Multi-Band", "Several scaled kHz/MHz/GHz-inspired layers are folded into an audible multiband representation.", "Reference frequency mappings", MatrixKind.BAND_SYMBOLIC, null, 7.83f),
    KHZ_LAYER("Kilohertz Layer", "Source is translated toward a configurable kHz acoustic band.", "Reference frequency mappings", MatrixKind.BAND_SYMBOLIC, 4000f, 7.83f),
    MHZ_LAYER("Megahertz Layer Symbolic", "MHz values are scale-mapped into an audible/acoustic representation.", "Reference frequency mappings", MatrixKind.BAND_SYMBOLIC, null, 7.83f),
    GHZ_LAYER("Gigahertz Layer Symbolic", "GHz values are scale-mapped into an audible/acoustic representation.", "Reference frequency mappings", MatrixKind.BAND_SYMBOLIC, null, 7.83f),
    THZ_LAYER("Terahertz Layer Symbolic", "THz values are scale-mapped into an audible/acoustic representation.", "Reference frequency mappings", MatrixKind.BAND_SYMBOLIC, null, 7.83f),
    ULTRASOUND_LAYER("Ultrasound Layer", "When hardware permits, the acoustic carrier is moved near the ultrasonic edge; otherwise it is folded into range.", "Acoustic band translation", MatrixKind.ULTRASONIC, 19000f, 7.83f),
    ELF_LAYER("Sub-Audible / ELF Layer", "Slow rates are represented as amplitude/phase modulation on an audible or ultrasonic acoustic carrier.", "Acoustic band translation", MatrixKind.BAND_SYMBOLIC, 18000f, 7.83f),
    SCHUMANN_LAYER("Schumann-Inspired Layer", "A Schumann-style envelope is available as a matrix layer for stacking.", "Reference frequency mappings", MatrixKind.BAND_SYMBOLIC, 18000f, 7.83f),
    MONTAGNIER_7HZ("7 Hz Reference", "A 7 Hz acoustic envelope from the transcript-derived Montagnier discussion.", "Reference frequency mappings", MatrixKind.BAND_SYMBOLIC, 18000f, 7f),
    SCHUMANN_7_8HZ("7–8 Hz Schumann Range", "A selectable 7–8 Hz acoustic modulation region.", "Reference frequency mappings", MatrixKind.BAND_SYMBOLIC, 18000f, 7.83f),
    PRESET_528("528 Hz Transcript Reference", "A 528 Hz acoustic reference preset preserved as transcript-derived metadata, without biological-effect claims.", "Reference frequency mappings", MatrixKind.RESONANCE, 528f, 7.83f),
    BAND_10_100KHZ("10–100 kHz Reference Band", "Out-of-device values are scale-mapped into the available acoustic band for visualization/sonification.", "Reference frequency mappings", MatrixKind.BAND_SYMBOLIC, null, 7.83f),
    BAND_640_700KHZ("640–700 kHz Reference Band", "The transcript's radio-range reference is scale-mapped into audio, not transmitted as RF.", "Reference frequency mappings", MatrixKind.BAND_SYMBOLIC, null, 7.83f),
    RF_CONVERSION_SYMBOLIC("Radio-Frequency Conversion Symbolic", "Audio is mapped into a virtual RF-carrier model and returned as acoustic modulation.", "Symbolic RF / carrier models", MatrixKind.BAND_SYMBOLIC, 18000f, 7.83f),
    BROADBAND_RADIO_SYMBOLIC("Broadband Radio Symbolic", "Information is spread across several acoustic proxy carriers.", "Symbolic RF / carrier models", MatrixKind.BAND_SYMBOLIC, 16000f, 7.83f),
    OPTICAL_TO_RADIO_SYMBOLIC("Optical → Radio → Sound", "A staged scale-mapping models the transcript's proposed optical-to-radio chain acoustically.", "Symbolic RF / carrier models", MatrixKind.BAND_SYMBOLIC, 16000f, 7.83f),
    AUDIO_TO_RF_SYMBOLIC("Audio → RF Modulation Symbolic", "Audio controls virtual AM/FM/phase data on an acoustic proxy carrier.", "Symbolic RF / carrier models", MatrixKind.HETERODYNE, 18000f, 7.83f),
    RF_TO_AUDIO_SYMBOLIC("RF → Audio Demodulation Symbolic", "A virtual modulated carrier is envelope/difference demodulated back to audible structure.", "Symbolic RF / carrier models", MatrixKind.HETERODYNE, 18000f, 7.83f),
    MICROWAVE_VISUAL("Microwave-Band Visualization", "Microwave-band labels are mapped to visible/acoustic proxies only.", "Symbolic RF / visualization", MatrixKind.BAND_SYMBOLIC, null, 7.83f),
    MILLIMETER_VISUAL("Millimeter-Wave Visualization", "Millimeter-wave labels are mapped to visible/acoustic proxies only.", "Symbolic RF / visualization", MatrixKind.BAND_SYMBOLIC, null, 7.83f),
    MOBILE_3G4G5G_OVERLAY("3G / 4G / 5G Spectrum Overlay", "Reference bands are shown as symbolic spectral markers, not transmitted.", "Symbolic RF / visualization", MatrixKind.BAND_SYMBOLIC, null, 7.83f),
    MICROWAVE_INTERFERENCE_SIM("Microwave Interference Simulation", "Interference geometry is represented with safe acoustic proxy carriers.", "Symbolic RF / visualization", MatrixKind.INTERFERENCE, 18000f, 7.83f),
    MICROWAVE_BIO_COMPARE("Microwave / Biological Spectrum Compare", "Two normalized software spectra are compared as visualization/sonification.", "Symbolic RF / visualization", MatrixKind.SPECTRAL, null, 7.83f),

    BROADBAND_SPECTRUM("Broadband Spectrum", "A wide harmonic frequency stack is synthesized from the source envelope.", "Spectral processing", MatrixKind.SPECTRAL, null, 7.83f),
    FREQUENCY_TRANSLATION("Frequency Translation", "Spectral content is shifted upward/downward while retaining envelope structure.", "Spectral processing", MatrixKind.HETERODYNE, 8000f, 7.83f),
    HETERODYNE_MATRIX("Heterodyne", "Two oscillators create sum/difference relationships around the source.", "Spectral processing", MatrixKind.HETERODYNE, 12000f, 7.83f),
    SIDEBAND_MATRIX("Sideband", "Carrier plus upper/lower information sidebands are generated acoustically.", "Spectral processing", MatrixKind.HETERODYNE, 12000f, 7.83f),
    ENVELOPE_EXTRACTION("Envelope Extraction", "Speech/music envelope is retained while carrier structure is replaced.", "Spectral processing", MatrixKind.SPECTRAL, 6000f, 7.83f),
    SPECTRAL_IMPRINT("Spectral Imprint", "A slowly captured spectral signature is imposed back onto the source envelope.", "Spectral processing", MatrixKind.SPECTRAL, null, 7.83f),
    SPECTRAL_MORPH("Spectral Morph", "The source continuously interpolates between ordered harmonic and noisy spectral signatures.", "Spectral processing", MatrixKind.SPECTRAL, null, 7.83f),
    CONVOLUTION_IMPRINT("Convolution Imprint", "A short self-derived impulse-style template colors later source audio.", "Spectral processing", MatrixKind.SPECTRAL, null, 7.83f),
    FFT_SIGNATURE("FFT Signature Capture", "Dominant spectral energy is tracked and converted into a narrow oscillator bank.", "Spectral analysis / auto", MatrixKind.SPECTRAL, null, 7.83f),
    SPECTROGRAM_RECON("Spectrogram → Sound Reconstruction", "Time-varying spectral bins are re-synthesized as an oscillator-bank approximation.", "Spectral analysis / auto", MatrixKind.SPECTRAL, null, 7.83f),
    REFERENCE_TARGET_MORPH("Reference vs Target Spectral Morph", "Source spectrum is progressively reorganized toward a stable harmonic reference template.", "Signature / comparison", MatrixKind.SIGNATURE, null, 7.83f),
    HEALTHY_REFERENCE_SIGNATURE("Reference Signature", "A reusable stable reference spectrum for comparison/morphing, not a medical diagnosis.", "Signature / comparison", MatrixKind.SIGNATURE, null, 7.83f),

    ACOUSTIC_ULTRASONIC_STACK("Acoustic + Ultrasonic Layer", "Audible source and near-ultrasonic acoustic carrier are layered together.", "Composite stacks", MatrixKind.ULTRASONIC, 19000f, 7.83f),
    ACOUSTIC_ELF_STACK("Acoustic + ELF Layer", "Direct audio is layered with a slow acoustic modulation envelope.", "Composite stacks", MatrixKind.BAND_SYMBOLIC, 12000f, 7.83f),
    ACOUSTIC_RF_SYMBOLIC_STACK("Acoustic + RF Symbolic Stack", "Direct audio plus several acoustic proxy carriers model a multi-domain stack.", "Composite stacks", MatrixKind.BAND_SYMBOLIC, 18000f, 7.83f),
    ACOUSTIC_LIGHT_SYNC("Acoustic + Light Synchronization", "Audio amplitude and phase are prepared for synchronized on-screen light pulses.", "Composite stacks", MatrixKind.LIGHT, null, 7.83f),
    BINAURAL_MATRIX("Binaural Matrix", "Independent left/right oscillator carriers encode the same source envelope with a selected difference rate.", "Stereo / spatial", MatrixKind.PHASE, 400f, 7f),
    COUNTER_ROTATING_STEREO("Counter-Rotating Stereo", "Opposite stereo phase and pan motion rotate around the source.", "Stereo / spatial", MatrixKind.PHASE, 6000f, 7.83f),
    TOROIDAL_VISUAL("Toroidal Audio Visualization", "Circulating oscillator rings are represented in phase and live visualization.", "Geometry / visualization", MatrixKind.GEOMETRY, 8000f, 7.83f),
    TORSION_INSPIRED("Torsion-Inspired", "Information is encoded through rotating stereo phase/polarization symbolism.", "Geometry / visualization", MatrixKind.GEOMETRY, 10000f, 7.83f),
    LONGITUDINAL_SIM("Longitudinal-Wave Simulation", "Compression/rarefaction style amplitude structure is sonified with opposed stereo pressure proxies.", "Geometry / visualization", MatrixKind.FIELD, 6000f, 7.83f),
    ELECTROSTATIC_SONIFICATION("Electrostatic-Field Sonification", "A virtual static-field bias controls oscillator asymmetry and pulse density.", "Field / sensor symbolic", MatrixKind.FIELD, 4000f, 7.83f),
    DC_FIELD_VIS("DC-Field Modulation Visualization", "A slowly changing software DC bias is mapped to phase/asymmetry.", "Field / sensor symbolic", MatrixKind.FIELD, null, .25f),
    REFERENCE_10KV("10,000 V Experiment Reference", "Transcript experiment voltage is retained as metadata and mapped to a safe acoustic scale only.", "Historical reference simulations", MatrixKind.FIELD, null, 7.83f),
    MAGNETIC_FIELD_SONIFICATION("Magnetic-Field Sonification", "A generic magnetic-field style value stream is mapped to frequency and stereo phase.", "Field / sensor symbolic", MatrixKind.FIELD, null, 7.83f),
    GEOMAGNETIC("Geomagnetic Mode", "Slow field-drift style modulation is layered over the source.", "Earth / field", MatrixKind.FIELD, null, 7.83f),
    HELIO_GEOMAGNETIC("Helio-Geomagnetic Mode", "Two slow drift oscillators represent solar/geomagnetic coupling symbolically.", "Earth / field", MatrixKind.FIELD, null, 7.83f),
    SCHUMANN_GEOMAGNETIC("Schumann + Geomagnetic", "Schumann-rate AM is combined with a much slower field-drift oscillator.", "Earth / field", MatrixKind.FIELD, 12000f, 7.83f),
    MORPHOGENETIC_FIELD("Morphogenetic-Field Visualization", "Many virtual cells share a common oscillator motif with controlled phase spread.", "Bio / field hypotheses", MatrixKind.BIO, null, 7.83f),
    CHROMOSOME_CONTINUUM("Chromosome Continuum", "A bank of synchronized oscillators represents many cells sharing one pattern.", "Bio / field hypotheses", MatrixKind.BIO, null, 7.83f),
    NONLOCALITY_VIS("Nonlocality Visualization", "Two separated software oscillators remain explicitly linked by shared parameters.", "Quantum-inspired simulation", MatrixKind.PHASE, 6000f, 7.83f),
    ENTANGLEMENT_PAIR("Entanglement-Inspired Pair", "Changing one software oscillator deterministically changes its paired oscillator; no quantum-entanglement claim.", "Quantum-inspired simulation", MatrixKind.PHASE, 6000f, 7.83f),
    QUANTUM_TELEPORT_VIS("Quantum-Teleportation Visualization", "State values are copied between virtual nodes with phase-transition animation/sonification.", "Quantum-inspired simulation", MatrixKind.PHASE, 6000f, 7.83f),

    COHERENCE_METER_AUDIO("Coherence Meter Sonification", "Phase order controls harmonic purity so increasing coherence becomes audible.", "Coherence / order", MatrixKind.COHERENCE, null, 7.83f),
    ENTROPY_COHERENCE("Entropy / Coherence", "Noise-like structure continuously reorganizes toward periodic phase order and back.", "Coherence / order", MatrixKind.COHERENCE, null, 7.83f),
    NEGENTROPY("Negentropy-Inspired", "A noisy input is progressively reorganized toward stable periodic structure.", "Coherence / order", MatrixKind.COHERENCE, null, 7.83f),
    BROWNIAN_BASELINE("Brownian / Random Baseline", "Random-walk modulation provides a comparison baseline.", "Noise / order comparison", MatrixKind.NOISE_ORDER, null, 7.83f),
    ORDERED_RANDOM_COMPARE("Ordered vs Random", "Crossfades between stochastic texture and periodic harmonic order.", "Noise / order comparison", MatrixKind.NOISE_ORDER, null, 7.83f),

    LIQUID_CRYSTAL_RESONANCE("Liquid-Crystal Resonance", "Layered anisotropic phase rotation is used as a liquid-crystal style visualization/sonification.", "Water / material hypotheses", MatrixKind.WATER, null, 7.83f),
    STRUCTURED_WATER("Structured-Water Visualization", "Slow coherent clusters and phase domains are represented acoustically.", "Water / material hypotheses", MatrixKind.WATER, null, 7.83f),
    EZ_WATER("EZ-Water Inspired", "Ordered-vs-random boundary layers are represented through coherence and spectral contrast.", "Water / material hypotheses", MatrixKind.WATER, null, 7.83f),
    WATER_BRIDGE_WAVEGUIDE("Water-Bridge Waveguide", "Two resonant nodes exchange a traveling-wave envelope across a virtual bridge.", "Water / material hypotheses", MatrixKind.WATER, 6000f, 7.83f),
    WATER_SIGNATURE("Water Signature", "A reusable source-derived spectral signature preset for water-related experiments.", "Signature library", MatrixKind.SIGNATURE, null, 7.83f),

    MEMBRANE_POTENTIAL_DATA("Membrane-Potential Data Sonification", "Imported measurement-style values are represented as pitch and pulse-rate changes.", "Bio / data sonification", MatrixKind.BIO, null, 7.83f),
    MITOCHONDRIAL_OSCILLATION("Mitochondrial Oscillation", "Coupled damped oscillators represent changing cellular-energy rhythms.", "Bio / data sonification", MatrixKind.BIO, null, 7.83f),
    BIOELECTRIC_FIELD("Bioelectric Field", "Multi-band source activity becomes a phase-linked field visualization/sonification.", "Bio / data sonification", MatrixKind.BIO, null, 7.83f),
    BIOPHOTON_BIOELECTRIC("Biophoton + Bioelectric", "Pulse-density and phase-field layers are coupled in one representation.", "Bio / data sonification", MatrixKind.BIO, null, 7.83f),
    MICROTUBULE_STANDING_WAVE("Microtubule Standing-Wave", "A multiband standing-wave visualizer/sonification using scaled reference bands.", "Bio / reference models", MatrixKind.INTERFERENCE, 8000f, 7.83f),

    TIME_STRETCH_RESONANCE("Time-Stretch Resonance", "Modulation state changes more slowly while preserving harmonic relationships.", "Time / memory", MatrixKind.TIME, null, 2f),
    TIME_COMPRESSION_RESONANCE("Time-Compression Resonance", "Modulation state changes more rapidly while preserving harmonic relationships.", "Time / memory", MatrixKind.TIME, null, 30f),
    REVERSE_TIME("Reverse-Time Audio", "Short source-derived motifs are mirrored in time inside the streaming processor.", "Time / memory", MatrixKind.TIME, null, 7.83f),
    TEMPORAL_MIRROR("Temporal Mirror", "Forward and short-delayed mirrored envelopes are paired in stereo.", "Time / memory", MatrixKind.TIME, null, 7.83f),
    FREQUENCY_MEMORY("Frequency Memory", "Tracked spectral energy decays slowly after the driving source changes.", "Time / memory", MatrixKind.MEMORY, null, 7.83f),
    PHANTOM_DNA("Phantom-DNA Visualization", "A decaying spectral/visual imprint remains after strong source activity falls away.", "Time / memory", MatrixKind.MEMORY, null, 7.83f),
    PHANTOM_LEAF("Phantom-Leaf Visualization", "A generic persistence effect leaves a fading sonified image-style imprint.", "Time / memory", MatrixKind.MEMORY, null, 7.83f),
    DYNAMIC_SCATTERING("Dynamic-Light-Scattering", "Changing distribution-like values are mapped into moving noise bands and resonances.", "Optical / statistical visualization", MatrixKind.NOISE_ORDER, null, 7.83f),
    LASER_CORRELATION("Laser Correlation Spectrum", "Correlation-like periodicities are converted to a narrow oscillator bank.", "Optical / statistical visualization", MatrixKind.SPECTRAL, null, 7.83f),
    DIFFRACTION_GRATING("Diffraction-Grating Mode", "Source spectrum controls a virtual diffraction spacing represented through harmonic combs.", "Optical / statistical visualization", MatrixKind.HOLOGRAM, 8000f, 7.83f),

    TSIEN_KANCHEN_GEOMETRY("Tsien Kanchen / Biotron Geometry", "A dodecahedral-style virtual routing network sends source energy through multiple phase vertices.", "Geometry / waveguide", MatrixKind.GEOMETRY, 8000f, 7.83f),
    GEOMETRY_RESONANCE("Geometry Resonance", "Sphere, torus, helix, dodecahedron and lattice routing profiles alter phase/modulation.", "Geometry / waveguide", MatrixKind.GEOMETRY, 8000f, 7.83f),
    WAVEGUIDE_SIM("Waveguide Simulation", "A resonant delayed path simulates propagation through a bounded guide.", "Geometry / waveguide", MatrixKind.GEOMETRY, 6000f, 7.83f),
    NEGATIVE_MASS_PHONON("Negative-Mass Phonon Visualization", "Counter-evolving oscillator energy provides a purely theoretical visualization.", "Phonon / theoretical", MatrixKind.RESONANCE, null, 7.83f),
    ACOUSTIC_LEVITATION_DISPLAY("Acoustic-Levitation Standing-Wave Display", "Standing-wave nodes are visualized/sonified without implying phone speakers can levitate objects.", "Geometry / waveguide", MatrixKind.INTERFERENCE, 4000f, 7.83f),

    HOMEOPATHIC_SIGNATURE("Homeopathic-Signature Sonification", "A supplied source signature can be stored/reused without claiming molecular transfer.", "Signature library", MatrixKind.SIGNATURE, null, 7.83f),
    HERB_SIGNATURE("Herb Signature", "Reusable source-derived spectral signature.", "Signature library", MatrixKind.SIGNATURE, null, 7.83f),
    MINERAL_SIGNATURE("Mineral Signature", "Reusable source-derived spectral signature.", "Signature library", MatrixKind.SIGNATURE, null, 7.83f),
    CRYSTAL_SIGNATURE("Crystal Signature", "Reusable source-derived spectral signature.", "Signature library", MatrixKind.SIGNATURE, null, 7.83f),
    COLOR_SIGNATURE("Color Signature", "Color-like metadata is converted to a reusable harmonic signature.", "Signature library", MatrixKind.SIGNATURE, null, 7.83f),
    FOOD_SIGNATURE("Food Signature", "Reusable source-derived spectral signature.", "Signature library", MatrixKind.SIGNATURE, null, 7.83f),
    ESSENTIAL_OIL_SIGNATURE("Essential-Oil Signature", "Reusable source-derived spectral signature.", "Signature library", MatrixKind.SIGNATURE, null, 7.83f),
    PLANT_FREQUENCY("Plant-Frequency Mode", "Source-derived periodicities are arranged into a slowly evolving harmonic signature.", "Signature library", MatrixKind.SIGNATURE, null, 7.83f),
    MUSIC_RESONANCE("Music Resonance", "Dominant musical frequencies are reinforced with related harmonics.", "Signature library", MatrixKind.RESONANCE, null, 7.83f),
    SPEECH_RESONANCE("Speech Resonance", "Speech-band formant/envelope energy drives a resonant carrier bank.", "Signature library", MatrixKind.RESONANCE, null, 7.83f),
    MANTRA_WORD_PATTERN("Mantra / Word Pattern", "Repeated speech envelopes are converted into stable rhythmic/harmonic motifs.", "Language / information", MatrixKind.LANGUAGE, null, 7.83f),

    AUTO_DOMINANT_DETECT("Automatic Dominant-Frequency Detection", "Tracks source periodicity and follows it with a soft resonator.", "Automatic matrix tools", MatrixKind.AUTO, null, 7.83f),
    AUTO_HARMONIC_EXTRACTION("Automatic Harmonic Extraction", "Builds harmonics around a tracked dominant periodicity.", "Automatic matrix tools", MatrixKind.AUTO, null, 7.83f),
    AUTO_RESONANCE("Automatic Resonance Generation", "Continuously tunes a damped resonator toward source activity.", "Automatic matrix tools", MatrixKind.AUTO, null, 7.83f),
    AUTO_PHASE_COHERENCE("Automatic Phase Coherence", "Progressively tightens stereo phase spread as source stability rises.", "Automatic matrix tools", MatrixKind.AUTO, null, 7.83f),
    AUTO_FRACTALIZE("Automatic Fractalization", "Copies the source envelope into nested time scales automatically.", "Automatic matrix tools", MatrixKind.AUTO, null, 7.83f),
    AUTO_SOLITON("Automatic Soliton Envelope", "Source transients seed stable traveling pulse envelopes automatically.", "Automatic matrix tools", MatrixKind.AUTO, 6000f, 4f),
    AUTO_SCHUMANN_ROUND("Automatic Schumann Rounding", "Tracked periodicities are folded toward the nearest selected Schumann-related rate.", "Automatic matrix tools", MatrixKind.AUTO, 18000f, 7.83f),
    AUTO_DNA_SCALAR_STACK("Automatic DNA / Scalar Stack", "Combines DNA-style information quantization, phase-paired carrier and slow envelope as one acoustic matrix.", "Automatic matrix tools", MatrixKind.AUTO, 18000f, 7.83f)
}

object MatrixPresetCatalog {
    fun preset(mode: MatrixMode): MethodPreset = MethodPreset(
        name = mode.label,
        category = mode.category,
        note = mode.description,
        carrierHz = mode.presetCarrier,
        rateHz = mode.presetRate,
        depth = mode.presetDepth,
        ditherDeg = if (mode.kind in setOf(MatrixKind.GEOMETRY, MatrixKind.PHASE, MatrixKind.HOLOGRAM, MatrixKind.POLARIZATION)) 6f else null,
        ditherRateHz = if (mode.kind in setOf(MatrixKind.GEOMETRY, MatrixKind.PHASE, MatrixKind.HOLOGRAM, MatrixKind.POLARIZATION)) .18f else null
    )
}
