package com.vaan.frequencyscope;
import android.Manifest;import android.app.*;import android.os.*;import android.content.pm.*;import android.graphics.*;import android.hardware.*;import android.media.*;import android.widget.*;import java.util.*;import java.util.concurrent.atomic.*;
public class MainActivity extends Activity implements SensorEventListener{
 static final int REQ=9001,N=16384,SN=256; TextView hz,meta,peaks,status; SpectrumView graph; Spinner mode; Button start,freeze; volatile boolean frozen=false; AudioRecord rec; Thread th; AtomicBoolean running=new AtomicBoolean(false); SensorManager sm; Sensor sensor; final ArrayList<Float> sv=new ArrayList<>(); long sensorT0; float smoothHz=0;
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(3,7,10));build();}
 TextView tv(String s,int sp,int col){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(col);v.setGravity(17);v.setPadding(8,8,8,8);return v;} Button bt(String s){Button b=new Button(this);b.setText(s);return b;}
 void build(){int bg=Color.rgb(5,8,12),fg=Color.rgb(225,240,245),ac=Color.rgb(0,255,200),mut=Color.rgb(140,170,180);ScrollView sc=new ScrollView(this);sc.setBackgroundColor(bg);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(16,16,16,20);sc.addView(root);root.addView(tv("FREQUENCY SCOPE v1.1",24,ac));root.addView(tv("LIVE ENVIRONMENTAL FREQUENCY ANALYZER",11,mut));hz=tv("— Hz",46,fg);root.addView(hz);meta=tv("Ready • tap START",13,mut);root.addView(meta);mode=new Spinner(this);mode.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"AUDIO Hz","VIBRATION Hz","MAG FIELD Hz"}));root.addView(mode,new LinearLayout.LayoutParams(-1,55));LinearLayout row=new LinearLayout(this);start=bt("START");freeze=bt("FREEZE");row.addView(start,new LinearLayout.LayoutParams(0,55,1));row.addView(freeze,new LinearLayout.LayoutParams(0,55,1));root.addView(row);graph=new SpectrumView(this);root.addView(graph,new LinearLayout.LayoutParams(-1,480));peaks=tv("Strongest frequencies will appear here in Hz",15,fg);root.addView(peaks);status=tv("Idle • choose a mode and tap START",12,mut);root.addView(status);start.setOnClickListener(v->{status.setText("START pressed • opening selected input…");meta.setText("Starting…");if(running.get()||sensor!=null||rec!=null)stop("Stopped");else begin();});freeze.setOnClickListener(v->{frozen=!frozen;freeze.setText(frozen?"UNFREEZE":"FREEZE");});setContentView(sc);}
 void begin(){int m=mode.getSelectedItemPosition();if(m==0){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){status.setText("Microphone permission required • requesting…");meta.setText("Grant microphone permission");requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ);return;}startAudio();}else startSensor(m==1?Sensor.TYPE_ACCELEROMETER:Sensor.TYPE_MAGNETIC_FIELD);}
 public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r!=REQ)return;if(g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED){status.setText("Microphone granted • opening input…");startAudio();}else{status.setText("MIC PERMISSION DENIED • allow Microphone in App info → Permissions, or use VIBRATION/MAG FIELD.");meta.setText("Audio permission blocked");start.setText("START");}}
 void startAudio(){stopAudio();int[] rates={48000,44100,32000};int[] sources={MediaRecorder.AudioSource.UNPROCESSED,MediaRecorder.AudioSource.VOICE_RECOGNITION,MediaRecorder.AudioSource.MIC,MediaRecorder.AudioSource.DEFAULT};Exception last=null;for(int rate:rates){int min=AudioRecord.getMinBufferSize(rate,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT);if(min<=0)continue;for(int source:sources){AudioRecord a=null;try{a=new AudioRecord(source,rate,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT,Math.max(min*2,N*2));if(a.getState()!=AudioRecord.STATE_INITIALIZED)throw new IllegalStateException("input not initialized");a.startRecording();if(a.getRecordingState()!=AudioRecord.RECORDSTATE_RECORDING)throw new IllegalStateException("input did not start");rec=a;launchAudio(rate,source);return;}catch(Exception e){last=e;if(a!=null)try{a.release();}catch(Exception ignored){}}}}String why=last==null?"no compatible audio input":String.valueOf(last.getMessage());status.setText("MIC OPEN FAILED • "+why);meta.setText("Try VIBRATION Hz to test scanner");start.setText("START");}
 void launchAudio(final int rate,final int source){running.set(true);start.setText("STOP");status.setText("LIVE AUDIO • "+src(source)+" • sampling "+rate+" times/sec");meta.setText("Collecting first frequency frame…");th=new Thread(()->{short[] s=new short[N];while(running.get()){int got=0;while(got<N&&running.get()){int x;try{x=rec.read(s,got,N-got,AudioRecord.READ_BLOCKING);}catch(Exception e){fail("Audio read failed: "+e.getMessage());return;}if(x>0)got+=x;else if(x<0){fail("Audio read error "+x);return;}}if(got==N)analyzeAudio(s,rate);}},"FrequencyScope-Audio");th.start();}
 String src(int s){if(s==MediaRecorder.AudioSource.UNPROCESSED)return"UNPROCESSED";if(s==MediaRecorder.AudioSource.VOICE_RECOGNITION)return"VOICE RECOGNITION";if(s==MediaRecorder.AudioSource.MIC)return"MIC";return"DEFAULT";}
 void fail(String s){runOnUiThread(()->{status.setText(s);meta.setText("Scanner stopped");running.set(false);start.setText("START");});}
 void analyzeAudio(short[] s,int rate){double[] r=new double[N],im=new double[N];double mean=0;for(short x:s)mean+=x;mean/=s.length;for(int i=0;i<N;i++){double win=.5-.5*Math.cos(2*Math.PI*i/(N-1));r[i]=((s[i]-mean)/32768.0)*win;}FFT.run(r,im);float[] mag=new float[N/2];for(int i=1;i<mag.length;i++)mag[i]=(float)(20*Math.log10(Math.hypot(r[i],im[i])/N+1e-12));showSpectrum(mag,rate,Math.min(20000,rate/2.0),"AUDIO");}
 void showSpectrum(float[] mag,double rate,double maxHz,String label){int lo=Math.max(1,(int)(15*mag.length*2/rate)),hi=Math.min(mag.length-2,(int)(maxHz*mag.length*2/rate));ArrayList<Integer> ids=new ArrayList<>();for(int i=lo;i<=hi;i++)if(mag[i]>mag[i-1]&&mag[i]>=mag[i+1])ids.add(i);ids.sort((a,b)->Float.compare(mag[b],mag[a]));if(ids.size()==0){runOnUiThread(()->meta.setText("LIVE • waiting for a stable frequency peak…"));return;}int k=ids.get(0);double y1=mag[k-1],y2=mag[k],y3=mag[k+1],den=y1-2*y2+y3,delta=Math.abs(den)<1e-9?0:.5*(y1-y3)/den;delta=Math.max(-.5,Math.min(.5,delta));double f=(k+delta)*rate/(mag.length*2.0);smoothHz=smoothHz==0?(float)f:(float)(.72*smoothHz+.28*f);StringBuilder ps=new StringBuilder();for(int n=0;n<Math.min(8,ids.size());n++){int q=ids.get(n);double yy1=mag[q-1],yy2=mag[q],yy3=mag[q+1],dd=yy1-2*yy2+yy3,di=Math.abs(dd)<1e-9?0:.5*(yy1-yy3)/dd;di=Math.max(-.5,Math.min(.5,di));double pf=(q+di)*rate/(mag.length*2.0);ps.append(String.format(Locale.US,"%d. %.2f Hz\n",n+1,pf));}final double ff=f;runOnUiThread(()->{if(frozen)return;hz.setText(String.format(Locale.US,"%.2f Hz",ff));meta.setText(String.format(Locale.US,"%s • smoothed %.2f Hz",label,smoothHz));peaks.setText(ps.toString());graph.set(mag,rate,maxHz);});}
 void startSensor(int type){sm=(SensorManager)getSystemService(SENSOR_SERVICE);sensor=sm.getDefaultSensor(type);if(sensor==null){status.setText("Selected sensor is not present on this phone.");meta.setText("Choose another mode");sensor=null;return;}sv.clear();sensorT0=System.nanoTime();boolean ok=sm.registerListener(this,sensor,SensorManager.SENSOR_DELAY_FASTEST);if(!ok){status.setText("Android did not start the selected sensor.");sensor=null;return;}start.setText("STOP");status.setText(type==Sensor.TYPE_ACCELEROMETER?"LIVE VIBRATION • collecting motion samples":"LIVE MAG FIELD • collecting magnetic samples");meta.setText("Collecting 0 / "+SN+" samples…");}
 public void onSensorChanged(SensorEvent e){float v=(float)Math.sqrt(e.values[0]*e.values[0]+e.values[1]*e.values[1]+e.values[2]*e.values[2]);sv.add(v);if(sv.size()%32==0&&sv.size()<SN){final int count=sv.size();runOnUiThread(()->meta.setText("Collecting "+count+" / "+SN+" samples…"));}if(sv.size()>=SN){long now=System.nanoTime();double rate=sv.size()/((now-sensorT0)/1e9);double[] r=new double[SN],im=new double[SN];double mean=0;for(float x:sv)mean+=x;mean/=sv.size();for(int i=0;i<SN;i++)r[i]=(sv.get(i)-mean)*(.5-.5*Math.cos(2*Math.PI*i/(SN-1)));FFT.run(r,im);float[] m=new float[SN/2];for(int i=1;i<m.length;i++)m[i]=(float)(20*Math.log10(Math.hypot(r[i],im[i])/SN+1e-12));sv.clear();sensorT0=now;showSpectrum(m,rate,rate/2,e.sensor.getType()==Sensor.TYPE_ACCELEROMETER?"VIBRATION":"MAG FIELD");}}
 public void onAccuracyChanged(Sensor s,int a){}
 void stopAudio(){running.set(false);if(rec!=null){try{rec.stop();}catch(Exception ignored){}try{rec.release();}catch(Exception ignored){}rec=null;}}
 void stop(String why){stopAudio();if(sm!=null)sm.unregisterListener(this);sensor=null;sv.clear();start.setText("START");status.setText(why);meta.setText("Ready");}
 protected void onDestroy(){stop("Stopped");super.onDestroy();}
}
