package com.vaan.frequencyscope;
import android.*;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.*;import android.graphics.*;import android.hardware.*;import android.media.*;import android.view.*;import android.widget.*;import java.util.*;import java.util.concurrent.atomic.*;
public class MainActivity extends Activity implements SensorEventListener{
 static final int REQ=9,SR=48000,N=16384; TextView hz,meta,peaks,status; SpectrumView graph; Spinner mode; Button start,freeze; volatile boolean frozen=false; AudioRecord rec; Thread th; AtomicBoolean running=new AtomicBoolean(false); SensorManager sm; Sensor sensor; final ArrayList<Float> sv=new ArrayList<>(); long sensorT0; float smoothHz=0;
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(3,7,10));build();}
 TextView tv(String s,int sp,int col){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(col);v.setGravity(17);v.setPadding(6,6,6,6);return v;} Button bt(String s){Button b=new Button(this);b.setText(s);return b;}
 void build(){int bg=Color.rgb(5,8,12),fg=Color.rgb(225,240,245),ac=Color.rgb(0,255,200),mut=Color.rgb(140,170,180);ScrollView sc=new ScrollView(this);sc.setBackgroundColor(bg);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(16,16,16,20);sc.addView(root);root.addView(tv("FREQUENCY SCOPE",24,ac));root.addView(tv("LIVE ENVIRONMENTAL SPECTRAL ANALYZER",11,mut));hz=tv("— Hz",44,fg);root.addView(hz);meta=tv("Tap START",13,mut);root.addView(meta);mode=new Spinner(this);mode.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"AUDIO","VIBRATION","MAG FIELD"}));root.addView(mode,new LinearLayout.LayoutParams(-1,55));LinearLayout row=new LinearLayout(this);start=bt("START");freeze=bt("FREEZE");row.addView(start,new LinearLayout.LayoutParams(0,55,1));row.addView(freeze,new LinearLayout.LayoutParams(0,55,1));root.addView(row);graph=new SpectrumView(this);root.addView(graph,new LinearLayout.LayoutParams(-1,480));peaks=tv("Strongest peaks will appear here",14,fg);root.addView(peaks);status=tv("Audio: up to microphone bandwidth • Vibration/Magnetic: sensor-rate limited",12,mut);root.addView(status);start.setOnClickListener(v->{if(running.get()||sensor!=null)stop();else begin();});freeze.setOnClickListener(v->{frozen=!frozen;freeze.setText(frozen?"UNFREEZE":"FREEZE");});setContentView(sc);}
 void begin(){int m=mode.getSelectedItemPosition();if(m==0){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ);return;}startAudio();}else startSensor(m==1?Sensor.TYPE_ACCELEROMETER:Sensor.TYPE_MAGNETIC_FIELD);}
 public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)startAudio();}
 void startAudio(){int min=AudioRecord.getMinBufferSize(SR,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT);rec=new AudioRecord(MediaRecorder.AudioSource.UNPROCESSED,SR,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT,Math.max(min,N*2));if(rec.getState()!=AudioRecord.STATE_INITIALIZED){rec.release();rec=new AudioRecord(MediaRecorder.AudioSource.DEFAULT,SR,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT,Math.max(min,N*2));}running.set(true);rec.startRecording();start.setText("STOP");status.setText("Scanning microphone • FFT 16384 • bin spacing 2.93 Hz • interpolated peak estimate");th=new Thread(()->{short[] s=new short[N];while(running.get()){int got=0;while(got<N&&running.get()){int x=rec.read(s,got,N-got);if(x>0)got+=x;}if(got==N)analyzeAudio(s);}},"fs-audio");th.start();}
 void analyzeAudio(short[] s){double[] r=new double[N],im=new double[N];for(int i=0;i<N;i++){double win=0.5-0.5*Math.cos(2*Math.PI*i/(N-1));r[i]=s[i]/32768.0*win;}FFT.run(r,im);float[] db=new float[N/2];for(int i=1;i<db.length;i++){double mag=Math.hypot(r[i],im[i])/N;db[i]=(float)(20*Math.log10(mag+1e-12));}showSpectrum(db,SR,20000);}
 void showSpectrum(float[] db,double rate,double maxHz){int lo=Math.max(1,(int)(20*db.length*2/rate)),hi=Math.min(db.length-2,(int)(maxHz*db.length*2/rate));ArrayList<Integer> ids=new ArrayList<>();for(int i=lo;i<=hi;i++)if(db[i]>db[i-1]&&db[i]>=db[i+1])ids.add(i);ids.sort((a,b)->Float.compare(db[b],db[a]));if(ids.size()==0)return;int k=ids.get(0);double y1=db[k-1],y2=db[k],y3=db[k+1],den=y1-2*y2+y3,delta=Math.abs(den)<1e-9?0:0.5*(y1-y3)/den;delta=Math.max(-.5,Math.min(.5,delta));double f=(k+delta)*rate/(db.length*2.0);smoothHz=smoothHz==0?(float)f:(float)(.75*smoothHz+.25*f);StringBuilder ps=new StringBuilder();for(int n=0;n<Math.min(8,ids.size());n++){int q=ids.get(n);ps.append(String.format(Locale.US,"%d. %.2f Hz   %.1f dB\n",n+1,q*rate/(db.length*2.0),db[q]));}final double ff=f;runOnUiThread(()->{if(frozen)return;hz.setText(String.format(Locale.US,"%.2f Hz",ff));meta.setText(note(ff)+"  •  smoothed "+String.format(Locale.US,"%.2f Hz",smoothHz));peaks.setText(ps.toString());graph.set(db,rate,maxHz);});}
 String note(double f){if(f<=0)return "";double n=69+12*Math.log(f/440.0)/Math.log(2);int m=(int)Math.round(n);String[] a={"C","C♯","D","D♯","E","F","F♯","G","G♯","A","A♯","B"};return a[(m%12+12)%12]+(m/12-1)+String.format(Locale.US," %+.1f¢",100*(n-m));}
 void startSensor(int type){sm=(SensorManager)getSystemService(SENSOR_SERVICE);sensor=sm.getDefaultSensor(type);if(sensor==null){status.setText("That sensor is not present on this phone.");return;}sv.clear();sensorT0=System.nanoTime();sm.registerListener(this,sensor,SensorManager.SENSOR_DELAY_FASTEST);start.setText("STOP");status.setText(type==Sensor.TYPE_ACCELEROMETER?"Scanning vibration from accelerometer":"Scanning magnetic-field fluctuations from magnetometer");}
 public void onSensorChanged(SensorEvent e){float v=(float)Math.sqrt(e.values[0]*e.values[0]+e.values[1]*e.values[1]+e.values[2]*e.values[2]);sv.add(v);if(sv.size()>=2048){long now=System.nanoTime();double rate=sv.size()/((now-sensorT0)/1e9);int n=2048;double[] r=new double[n],im=new double[n];double mean=0;for(float x:sv)mean+=x;mean/=sv.size();for(int i=0;i<n;i++)r[i]=(sv.get(i)-mean)*(0.5-0.5*Math.cos(2*Math.PI*i/(n-1)));FFT.run(r,im);float[] d=new float[n/2];for(int i=1;i<d.length;i++)d[i]=(float)(20*Math.log10(Math.hypot(r[i],im[i])/n+1e-12));sv.clear();sensorT0=now;showSpectrum(d,rate,rate/2);}}
 public void onAccuracyChanged(Sensor s,int a){}
 void stop(){running.set(false);if(rec!=null){try{rec.stop();}catch(Exception ignored){}rec.release();rec=null;}if(sm!=null)sm.unregisterListener(this);sensor=null;start.setText("START");status.setText("Stopped");}
 protected void onDestroy(){stop();super.onDestroy();}
}
